name: Test

on:
  workflow_dispatch:

jobs:
  publish-nuget:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
        with:
          fetch-depth: 1
      - name: Pack
        run: |
          dotnet pack
          ls bin\Release